# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '\\isln-smb\aw_config\Git_Live_Code\Software\Maya\Scripts\Tools\Vray_Scene_States_Manager\Vray_Scene_State_Manager.ui'
#
# Created: Mon Dec 12 15:19:32 2016
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Vray_Scene_State_Manager(object):
	def setupUi(self, Vray_Scene_State_Manager):
		Vray_Scene_State_Manager.setObjectName("Vray_Scene_State_Manager")
		Vray_Scene_State_Manager.resize(1346, 871)
		self.centralwidget = QtWidgets.QWidget(Vray_Scene_State_Manager)
		self.centralwidget.setObjectName("centralwidget")
		self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.centralwidget)
		self.verticalLayout_10.setObjectName("verticalLayout_10")
		self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.splitter_3.sizePolicy().hasHeightForWidth())
		self.splitter_3.setSizePolicy(sizePolicy)
		self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
		self.splitter_3.setObjectName("splitter_3")
		self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
		self.splitter_2.setSizePolicy(sizePolicy)
		self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
		self.splitter_2.setHandleWidth(11)
		self.splitter_2.setObjectName("splitter_2")
		self.Asset_Tree_frame = QtWidgets.QFrame(self.splitter_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(2)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.Asset_Tree_frame.sizePolicy().hasHeightForWidth())
		self.Asset_Tree_frame.setSizePolicy(sizePolicy)
		self.Asset_Tree_frame.setFrameShape(QtWidgets.QFrame.Box)
		self.Asset_Tree_frame.setFrameShadow(QtWidgets.QFrame.Plain)
		self.Asset_Tree_frame.setObjectName("Asset_Tree_frame")
		self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Asset_Tree_frame)
		self.verticalLayout_4.setSpacing(0)
		self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.Asset_Tree_groupBox = QtWidgets.QGroupBox(self.Asset_Tree_frame)
		self.Asset_Tree_groupBox.setAlignment(QtCore.Qt.AlignCenter)
		self.Asset_Tree_groupBox.setObjectName("Asset_Tree_groupBox")
		self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Asset_Tree_groupBox)
		self.verticalLayout_3.setSpacing(0)
		self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.asset_tree_view = Asset_Tree_View(self.Asset_Tree_groupBox)
		self.asset_tree_view.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
		self.asset_tree_view.setDefaultDropAction(QtCore.Qt.IgnoreAction)
		self.asset_tree_view.setSortingEnabled(True)
		self.asset_tree_view.setObjectName("asset_tree_view")
		self.verticalLayout_3.addWidget(self.asset_tree_view)
		self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_2.setSpacing(3)
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.add_asset_Button = QtWidgets.QPushButton(self.Asset_Tree_groupBox)
		self.add_asset_Button.setObjectName("add_asset_Button")
		self.horizontalLayout_2.addWidget(self.add_asset_Button)
		self.add_child_asset_Button = QtWidgets.QPushButton(self.Asset_Tree_groupBox)
		self.add_child_asset_Button.setEnabled(False)
		self.add_child_asset_Button.setObjectName("add_child_asset_Button")
		self.horizontalLayout_2.addWidget(self.add_child_asset_Button)
		self.verticalLayout_3.addLayout(self.horizontalLayout_2)
		self.remove_asset_Button = QtWidgets.QPushButton(self.Asset_Tree_groupBox)
		self.remove_asset_Button.setObjectName("remove_asset_Button")
		self.verticalLayout_3.addWidget(self.remove_asset_Button)
		self.verticalLayout_4.addWidget(self.Asset_Tree_groupBox)
		self.Render_States_frame = QtWidgets.QFrame(self.splitter_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.Render_States_frame.sizePolicy().hasHeightForWidth())
		self.Render_States_frame.setSizePolicy(sizePolicy)
		self.Render_States_frame.setFrameShape(QtWidgets.QFrame.Box)
		self.Render_States_frame.setFrameShadow(QtWidgets.QFrame.Plain)
		self.Render_States_frame.setObjectName("Render_States_frame")
		self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.Render_States_frame)
		self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_9.setObjectName("verticalLayout_9")
		self.Render_States_groupBox = QtWidgets.QGroupBox(self.Render_States_frame)
		self.Render_States_groupBox.setAlignment(QtCore.Qt.AlignCenter)
		self.Render_States_groupBox.setObjectName("Render_States_groupBox")
		self.Render_Layers_groupBox_verticalLayout = QtWidgets.QVBoxLayout(self.Render_States_groupBox)
		self.Render_Layers_groupBox_verticalLayout.setSpacing(0)
		self.Render_Layers_groupBox_verticalLayout.setContentsMargins(3, 3, 3, 3)
		self.Render_Layers_groupBox_verticalLayout.setObjectName("Render_Layers_groupBox_verticalLayout")
		self.render_layer_helper_button = QtWidgets.QPushButton(self.Render_States_groupBox)
		self.render_layer_helper_button.setEnabled(False)
		self.render_layer_helper_button.setObjectName("render_layer_helper_button")
		self.Render_Layers_groupBox_verticalLayout.addWidget(self.render_layer_helper_button)
		self.isolateSelect_Button = QtWidgets.QPushButton(self.Render_States_groupBox)
		self.isolateSelect_Button.setCheckable(True)
		self.isolateSelect_Button.setObjectName("isolateSelect_Button")
		self.Render_Layers_groupBox_verticalLayout.addWidget(self.isolateSelect_Button)
		self.Hide_Unasined_Layers_Button = QtWidgets.QPushButton(self.Render_States_groupBox)
		self.Hide_Unasined_Layers_Button.setObjectName("Hide_Unasined_Layers_Button")
		self.Render_Layers_groupBox_verticalLayout.addWidget(self.Hide_Unasined_Layers_Button)
		self.Show_All_Display_Layers_Button = QtWidgets.QPushButton(self.Render_States_groupBox)
		self.Show_All_Display_Layers_Button.setObjectName("Show_All_Display_Layers_Button")
		self.Render_Layers_groupBox_verticalLayout.addWidget(self.Show_All_Display_Layers_Button)
		self.Render_States_Filter_groupBox = QtWidgets.QGroupBox(self.Render_States_groupBox)
		self.Render_States_Filter_groupBox.setAlignment(QtCore.Qt.AlignCenter)
		self.Render_States_Filter_groupBox.setObjectName("Render_States_Filter_groupBox")
		self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Render_States_Filter_groupBox)
		self.horizontalLayout_4.setSpacing(0)
		self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		self.Render_States_Filter_input = QtWidgets.QLineEdit(self.Render_States_Filter_groupBox)
		self.Render_States_Filter_input.setObjectName("Render_States_Filter_input")
		self.horizontalLayout_4.addWidget(self.Render_States_Filter_input)
		self.Favorits_Only_checkBox = QtWidgets.QCheckBox(self.Render_States_Filter_groupBox)
		self.Favorits_Only_checkBox.setObjectName("Favorits_Only_checkBox")
		self.horizontalLayout_4.addWidget(self.Favorits_Only_checkBox)
		self.Render_Layers_groupBox_verticalLayout.addWidget(self.Render_States_Filter_groupBox)
		self.render_states_view = Render_States_List_View(self.Render_States_groupBox)
		self.render_states_view.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
		self.render_states_view.setObjectName("render_states_view")
		self.Render_Layers_groupBox_verticalLayout.addWidget(self.render_states_view)
		self.horizontalLayout = QtWidgets.QHBoxLayout()
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.add_render_state_Button = QtWidgets.QPushButton(self.Render_States_groupBox)
		self.add_render_state_Button.setObjectName("add_render_state_Button")
		self.horizontalLayout.addWidget(self.add_render_state_Button)
		self.remove_render_state_Button = QtWidgets.QPushButton(self.Render_States_groupBox)
		self.remove_render_state_Button.setObjectName("remove_render_state_Button")
		self.horizontalLayout.addWidget(self.remove_render_state_Button)
		self.Render_Layers_groupBox_verticalLayout.addLayout(self.horizontalLayout)
		self.verticalLayout_9.addWidget(self.Render_States_groupBox)
		self.splitter = QtWidgets.QSplitter(self.splitter_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
		self.splitter.setSizePolicy(sizePolicy)
		self.splitter.setOrientation(QtCore.Qt.Vertical)
		self.splitter.setObjectName("splitter")
		self.Beauty_Overide_frame = QtWidgets.QFrame(self.splitter)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.Beauty_Overide_frame.sizePolicy().hasHeightForWidth())
		self.Beauty_Overide_frame.setSizePolicy(sizePolicy)
		self.Beauty_Overide_frame.setFrameShape(QtWidgets.QFrame.Box)
		self.Beauty_Overide_frame.setFrameShadow(QtWidgets.QFrame.Plain)
		self.Beauty_Overide_frame.setObjectName("Beauty_Overide_frame")
		self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Beauty_Overide_frame)
		self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_5.setObjectName("verticalLayout_5")
		self.Beauty_Overide_groupBox = QtWidgets.QGroupBox(self.Beauty_Overide_frame)
		self.Beauty_Overide_groupBox.setAlignment(QtCore.Qt.AlignCenter)
		self.Beauty_Overide_groupBox.setObjectName("Beauty_Overide_groupBox")
		self.Beauty_groupBox_verticalLayout = QtWidgets.QVBoxLayout(self.Beauty_Overide_groupBox)
		self.Beauty_groupBox_verticalLayout.setContentsMargins(3, 3, 3, 3)
		self.Beauty_groupBox_verticalLayout.setObjectName("Beauty_groupBox_verticalLayout")
		self.beauty_overide_view = Beauty_Overide_View(self.Beauty_Overide_groupBox)
		self.beauty_overide_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
		self.beauty_overide_view.setDragEnabled(True)
		self.beauty_overide_view.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
		self.beauty_overide_view.setDefaultDropAction(QtCore.Qt.IgnoreAction)
		self.beauty_overide_view.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
		self.beauty_overide_view.setProperty("view_state_type", 1)
		self.beauty_overide_view.setObjectName("beauty_overide_view")
		self.Beauty_groupBox_verticalLayout.addWidget(self.beauty_overide_view)
		self.verticalLayout_5.addWidget(self.Beauty_Overide_groupBox)
		self.Matte_Overide_frame = QtWidgets.QFrame(self.splitter)
		self.Matte_Overide_frame.setFrameShape(QtWidgets.QFrame.Box)
		self.Matte_Overide_frame.setFrameShadow(QtWidgets.QFrame.Plain)
		self.Matte_Overide_frame.setObjectName("Matte_Overide_frame")
		self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Matte_Overide_frame)
		self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_6.setObjectName("verticalLayout_6")
		self.Matte_Overide_groupBox = QtWidgets.QGroupBox(self.Matte_Overide_frame)
		self.Matte_Overide_groupBox.setAlignment(QtCore.Qt.AlignCenter)
		self.Matte_Overide_groupBox.setObjectName("Matte_Overide_groupBox")
		self.Matte_groupBox_verticalLayout = QtWidgets.QVBoxLayout(self.Matte_Overide_groupBox)
		self.Matte_groupBox_verticalLayout.setContentsMargins(3, 3, 3, 3)
		self.Matte_groupBox_verticalLayout.setObjectName("Matte_groupBox_verticalLayout")
		self.matte_overide_view = Matte_Overide_View(self.Matte_Overide_groupBox)
		self.matte_overide_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
		self.matte_overide_view.setDragEnabled(True)
		self.matte_overide_view.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
		self.matte_overide_view.setDefaultDropAction(QtCore.Qt.IgnoreAction)
		self.matte_overide_view.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
		self.matte_overide_view.setProperty("view_state_type", 2)
		self.matte_overide_view.setObjectName("matte_overide_view")
		self.Matte_groupBox_verticalLayout.addWidget(self.matte_overide_view)
		self.verticalLayout_6.addWidget(self.Matte_Overide_groupBox)
		self.Invisible_Overide_frame = QtWidgets.QFrame(self.splitter)
		self.Invisible_Overide_frame.setFrameShape(QtWidgets.QFrame.Box)
		self.Invisible_Overide_frame.setFrameShadow(QtWidgets.QFrame.Plain)
		self.Invisible_Overide_frame.setObjectName("Invisible_Overide_frame")
		self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Invisible_Overide_frame)
		self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_7.setObjectName("verticalLayout_7")
		self.Invisible_Overide_groupBox = QtWidgets.QGroupBox(self.Invisible_Overide_frame)
		self.Invisible_Overide_groupBox.setAlignment(QtCore.Qt.AlignCenter)
		self.Invisible_Overide_groupBox.setObjectName("Invisible_Overide_groupBox")
		self.Invisible_groupBox_verticalLayout = QtWidgets.QVBoxLayout(self.Invisible_Overide_groupBox)
		self.Invisible_groupBox_verticalLayout.setContentsMargins(3, 3, 3, 3)
		self.Invisible_groupBox_verticalLayout.setObjectName("Invisible_groupBox_verticalLayout")
		self.invisible_overide_view = Invisible_Overide_View(self.Invisible_Overide_groupBox)
		self.invisible_overide_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
		self.invisible_overide_view.setDragEnabled(True)
		self.invisible_overide_view.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
		self.invisible_overide_view.setDefaultDropAction(QtCore.Qt.IgnoreAction)
		self.invisible_overide_view.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
		self.invisible_overide_view.setProperty("view_state_type", 3)
		self.invisible_overide_view.setObjectName("invisible_overide_view")
		self.Invisible_groupBox_verticalLayout.addWidget(self.invisible_overide_view)
		self.verticalLayout_7.addWidget(self.Invisible_Overide_groupBox)
		self.Part_Sets_frame = QtWidgets.QFrame(self.splitter_2)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.Part_Sets_frame.sizePolicy().hasHeightForWidth())
		self.Part_Sets_frame.setSizePolicy(sizePolicy)
		self.Part_Sets_frame.setFrameShape(QtWidgets.QFrame.Box)
		self.Part_Sets_frame.setFrameShadow(QtWidgets.QFrame.Plain)
		self.Part_Sets_frame.setObjectName("Part_Sets_frame")
		self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Part_Sets_frame)
		self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_8.setObjectName("verticalLayout_8")
		self.Part_Sets_groupBox = QtWidgets.QGroupBox(self.Part_Sets_frame)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.Part_Sets_groupBox.sizePolicy().hasHeightForWidth())
		self.Part_Sets_groupBox.setSizePolicy(sizePolicy)
		self.Part_Sets_groupBox.setAlignment(QtCore.Qt.AlignCenter)
		self.Part_Sets_groupBox.setObjectName("Part_Sets_groupBox")
		self.Part_Sets_groupBox_verticalLayout = QtWidgets.QVBoxLayout(self.Part_Sets_groupBox)
		self.Part_Sets_groupBox_verticalLayout.setSpacing(0)
		self.Part_Sets_groupBox_verticalLayout.setContentsMargins(3, 3, 3, 3)
		self.Part_Sets_groupBox_verticalLayout.setObjectName("Part_Sets_groupBox_verticalLayout")
		self.part_sets_view = Part_Sets_List_View(self.Part_Sets_groupBox)
		self.part_sets_view.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
		self.part_sets_view.setDragEnabled(True)
		self.part_sets_view.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
		self.part_sets_view.setDefaultDropAction(QtCore.Qt.IgnoreAction)
		self.part_sets_view.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
		self.part_sets_view.setProperty("view_state_type", 0)
		self.part_sets_view.setObjectName("part_sets_view")
		self.Part_Sets_groupBox_verticalLayout.addWidget(self.part_sets_view)
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
		self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.add_part_set_Button = QtWidgets.QPushButton(self.Part_Sets_groupBox)
		self.add_part_set_Button.setObjectName("add_part_set_Button")
		self.horizontalLayout_3.addWidget(self.add_part_set_Button)
		self.remove_part_sets_Button = QtWidgets.QPushButton(self.Part_Sets_groupBox)
		self.remove_part_sets_Button.setObjectName("remove_part_sets_Button")
		self.horizontalLayout_3.addWidget(self.remove_part_sets_Button)
		self.Part_Sets_groupBox_verticalLayout.addLayout(self.horizontalLayout_3)
		self.verticalLayout_8.addWidget(self.Part_Sets_groupBox)
		self.verticalLayout_10.addWidget(self.splitter_3)
		self.entity_tree_view = Entity_Tree_View(self.centralwidget)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.entity_tree_view.sizePolicy().hasHeightForWidth())
		self.entity_tree_view.setSizePolicy(sizePolicy)
		self.entity_tree_view.setObjectName("entity_tree_view")
		self.verticalLayout_10.addWidget(self.entity_tree_view)
		Vray_Scene_State_Manager.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(Vray_Scene_State_Manager)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 1346, 26))
		self.menubar.setObjectName("menubar")
		self.menuItems = QtWidgets.QMenu(self.menubar)
		self.menuItems.setObjectName("menuItems")
		self.menuEdit = QtWidgets.QMenu(self.menubar)
		self.menuEdit.setObjectName("menuEdit")
		self.menuFile = QtWidgets.QMenu(self.menubar)
		self.menuFile.setObjectName("menuFile")
		self.menuViewport_Settings = QtWidgets.QMenu(self.menubar)
		self.menuViewport_Settings.setEnabled(False)
		self.menuViewport_Settings.setObjectName("menuViewport_Settings")
		Vray_Scene_State_Manager.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(Vray_Scene_State_Manager)
		self.statusbar.setObjectName("statusbar")
		Vray_Scene_State_Manager.setStatusBar(self.statusbar)
		self.actionAdd_Render_State = QtWidgets.QAction(Vray_Scene_State_Manager)
		self.actionAdd_Render_State.setObjectName("actionAdd_Render_State")
		self.actionAdd_Part_Set = QtWidgets.QAction(Vray_Scene_State_Manager)
		self.actionAdd_Part_Set.setObjectName("actionAdd_Part_Set")
		self.actionUndo = QtWidgets.QAction(Vray_Scene_State_Manager)
		self.actionUndo.setEnabled(False)
		self.actionUndo.setObjectName("actionUndo")
		self.actionRedo = QtWidgets.QAction(Vray_Scene_State_Manager)
		self.actionRedo.setEnabled(False)
		self.actionRedo.setObjectName("actionRedo")
		self.actionOpen_File = QtWidgets.QAction(Vray_Scene_State_Manager)
		self.actionOpen_File.setEnabled(False)
		self.actionOpen_File.setObjectName("actionOpen_File")
		self.actionSave = QtWidgets.QAction(Vray_Scene_State_Manager)
		self.actionSave.setEnabled(True)
		self.actionSave.setObjectName("actionSave")
		self.actionDelete_Parts = QtWidgets.QAction(Vray_Scene_State_Manager)
		self.actionDelete_Parts.setObjectName("actionDelete_Parts")
		self.actionRemove_Selected_States = QtWidgets.QAction(Vray_Scene_State_Manager)
		self.actionRemove_Selected_States.setObjectName("actionRemove_Selected_States")
		self.actionAdd_Asset = QtWidgets.QAction(Vray_Scene_State_Manager)
		self.actionAdd_Asset.setObjectName("actionAdd_Asset")
		self.action_Add_Child_Asset = QtWidgets.QAction(Vray_Scene_State_Manager)
		self.action_Add_Child_Asset.setObjectName("action_Add_Child_Asset")
		self.actionRemove_Selected_Asset = QtWidgets.QAction(Vray_Scene_State_Manager)
		self.actionRemove_Selected_Asset.setObjectName("actionRemove_Selected_Asset")
		self.actionDisplay_Layers_To_Part_Sets = QtWidgets.QAction(Vray_Scene_State_Manager)
		self.actionDisplay_Layers_To_Part_Sets.setObjectName("actionDisplay_Layers_To_Part_Sets")
		self.action_auto_frame_toggle = QtWidgets.QAction(Vray_Scene_State_Manager)
		self.action_auto_frame_toggle.setCheckable(True)
		self.action_auto_frame_toggle.setObjectName("action_auto_frame_toggle")
		self.action_Frame_Selected = QtWidgets.QAction(Vray_Scene_State_Manager)
		self.action_Frame_Selected.setObjectName("action_Frame_Selected")
		self.action_Frame_Visable = QtWidgets.QAction(Vray_Scene_State_Manager)
		self.action_Frame_Visable.setObjectName("action_Frame_Visable")
		self.actionLoad = QtWidgets.QAction(Vray_Scene_State_Manager)
		self.actionLoad.setObjectName("actionLoad")
		self.action_Sync_Display_Layers = QtWidgets.QAction(Vray_Scene_State_Manager)
		self.action_Sync_Display_Layers.setObjectName("action_Sync_Display_Layers")
		self.menuItems.addAction(self.actionAdd_Asset)
		self.menuItems.addAction(self.action_Add_Child_Asset)
		self.menuItems.addAction(self.actionRemove_Selected_Asset)
		self.menuItems.addAction(self.actionAdd_Part_Set)
		self.menuItems.addAction(self.actionDelete_Parts)
		self.menuItems.addAction(self.actionAdd_Render_State)
		self.menuItems.addAction(self.actionRemove_Selected_States)
		self.menuItems.addAction(self.actionDisplay_Layers_To_Part_Sets)
		self.menuItems.addAction(self.action_Sync_Display_Layers)
		self.menuEdit.addAction(self.actionUndo)
		self.menuEdit.addAction(self.actionRedo)
		self.menuEdit.addSeparator()
		self.menuFile.addAction(self.actionSave)
		self.menuFile.addAction(self.actionLoad)
		self.menuViewport_Settings.addAction(self.action_Frame_Selected)
		self.menuViewport_Settings.addAction(self.action_Frame_Visable)
		self.menuViewport_Settings.addAction(self.action_auto_frame_toggle)
		self.menubar.addAction(self.menuFile.menuAction())
		self.menubar.addAction(self.menuItems.menuAction())
		self.menubar.addAction(self.menuEdit.menuAction())
		self.menubar.addAction(self.menuViewport_Settings.menuAction())

		self.retranslateUi(Vray_Scene_State_Manager)
		QtCore.QObject.connect(self.actionAdd_Part_Set, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.add_Part_Set)
		QtCore.QObject.connect(self.actionUndo, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.undo_it)
		QtCore.QObject.connect(self.actionRedo, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.redo_it)
		QtCore.QObject.connect(self.actionAdd_Render_State, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.add_Render_State)
		QtCore.QObject.connect(self.actionOpen_File, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.open_File)
		QtCore.QObject.connect(self.actionSave, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.Save)
		QtCore.QObject.connect(self.actionDelete_Parts, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.Remove_Selected_Part_Sets)
		QtCore.QObject.connect(self.actionRemove_Selected_States, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.Remove_Selected_Render_States)
		QtCore.QObject.connect(self.actionAdd_Asset, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.add_Asset)
		QtCore.QObject.connect(self.add_render_state_Button, QtCore.SIGNAL("clicked()"), self.actionAdd_Render_State.trigger)
		QtCore.QObject.connect(self.remove_render_state_Button, QtCore.SIGNAL("clicked()"), self.actionRemove_Selected_States.trigger)
		QtCore.QObject.connect(self.add_part_set_Button, QtCore.SIGNAL("clicked()"), self.actionAdd_Part_Set.trigger)
		QtCore.QObject.connect(self.remove_part_sets_Button, QtCore.SIGNAL("clicked()"), self.actionDelete_Parts.trigger)
		QtCore.QObject.connect(Vray_Scene_State_Manager, QtCore.SIGNAL("ACTIVATE_RUN_SETUP(QMainWindow*)"), self.entity_tree_view._run_setup)
		QtCore.QObject.connect(Vray_Scene_State_Manager, QtCore.SIGNAL("ACTIVATE_RUN_SETUP(QMainWindow*)"), self.beauty_overide_view._run_setup)
		QtCore.QObject.connect(Vray_Scene_State_Manager, QtCore.SIGNAL("ACTIVATE_RUN_SETUP(QMainWindow*)"), self.matte_overide_view._run_setup)
		QtCore.QObject.connect(Vray_Scene_State_Manager, QtCore.SIGNAL("ACTIVATE_RUN_SETUP(QMainWindow*)"), self.invisible_overide_view._run_setup)
		QtCore.QObject.connect(Vray_Scene_State_Manager, QtCore.SIGNAL("ACTIVATE_RUN_SETUP(QMainWindow*)"), self.part_sets_view._run_setup)
		QtCore.QObject.connect(Vray_Scene_State_Manager, QtCore.SIGNAL("ACTIVATE_RUN_SETUP(QMainWindow*)"), self.render_states_view._run_setup)
		QtCore.QObject.connect(Vray_Scene_State_Manager, QtCore.SIGNAL("ACTIVATE_RUN_SETUP(QMainWindow*)"), self.asset_tree_view._run_setup)
		QtCore.QObject.connect(self.action_Add_Child_Asset, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.add_Child_Asset)
		QtCore.QObject.connect(self.add_child_asset_Button, QtCore.SIGNAL("clicked()"), self.action_Add_Child_Asset.trigger)
		QtCore.QObject.connect(self.add_asset_Button, QtCore.SIGNAL("clicked()"), self.actionAdd_Asset.trigger)
		QtCore.QObject.connect(self.asset_tree_view, QtCore.SIGNAL("ACTIVE_ITEM_CHANGED(QStandardItem*)"), self.render_states_view.Update_On_Active_Item_Changed)
		QtCore.QObject.connect(self.render_states_view, QtCore.SIGNAL("ACTIVE_ITEM_CHANGED(QStandardItem*)"), self.beauty_overide_view.Update_On_Active_Item_Changed)
		QtCore.QObject.connect(self.render_states_view, QtCore.SIGNAL("ACTIVE_ITEM_CHANGED(QStandardItem*)"), self.matte_overide_view.Update_On_Active_Item_Changed)
		QtCore.QObject.connect(self.render_states_view, QtCore.SIGNAL("ACTIVE_ITEM_CHANGED(QStandardItem*)"), self.invisible_overide_view.Update_On_Active_Item_Changed)
		QtCore.QObject.connect(self.render_states_view, QtCore.SIGNAL("ACTIVE_ITEM_CHANGED(QStandardItem*)"), self.part_sets_view.Update_On_Active_Item_Changed)
		QtCore.QObject.connect(self.actionRemove_Selected_Asset, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.Remove_Selected_Assets)
		QtCore.QObject.connect(self.remove_asset_Button, QtCore.SIGNAL("clicked()"), self.actionRemove_Selected_Asset.trigger)
		QtCore.QObject.connect(self.actionDisplay_Layers_To_Part_Sets, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.Construct_From_Display_Layers)
		QtCore.QObject.connect(self.actionLoad, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.Load)
		QtCore.QObject.connect(self.action_Sync_Display_Layers, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.sync_Display_Layers)
		QtCore.QObject.connect(self.Hide_Unasined_Layers_Button, QtCore.SIGNAL("clicked()"), Vray_Scene_State_Manager.Apply_Current_State_To_Diaplay_Layers)
		QtCore.QObject.connect(self.Show_All_Display_Layers_Button, QtCore.SIGNAL("clicked()"), Vray_Scene_State_Manager.Show_All_Diaplay_Layers)
		QtCore.QMetaObject.connectSlotsByName(Vray_Scene_State_Manager)

	def retranslateUi(self, Vray_Scene_State_Manager):
		Vray_Scene_State_Manager.setWindowTitle(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "MainWindow", None, -1))
		self.Asset_Tree_groupBox.setTitle(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Asset Tree", None, -1))
		self.add_asset_Button.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Add Asset", None, -1))
		self.add_child_asset_Button.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Add Child Asset", None, -1))
		self.remove_asset_Button.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Remove Selected Asset", None, -1))
		self.Render_States_groupBox.setTitle(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Render States", None, -1))
		self.render_layer_helper_button.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Build Render Layer Helper", None, -1))
		self.isolateSelect_Button.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Isolate Selected", None, -1))
		self.Hide_Unasined_Layers_Button.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Hide Unasined", None, -1))
		self.Show_All_Display_Layers_Button.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Show All Display Layers", None, -1))
		self.Render_States_Filter_groupBox.setTitle(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Filter", None, -1))
		self.Favorits_Only_checkBox.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Favorits Only", None, -1))
		self.add_render_state_Button.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Add Render State", None, -1))
		self.remove_render_state_Button.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Remove Selected", None, -1))
		self.Beauty_Overide_groupBox.setTitle(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Beauty Part Sets", None, -1))
		self.Matte_Overide_groupBox.setTitle(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Matte Part Sets", None, -1))
		self.Invisible_Overide_groupBox.setTitle(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Invisible Part Sets", None, -1))
		self.Part_Sets_groupBox.setTitle(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Unasied Part Sets", None, -1))
		self.add_part_set_Button.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Add Part Set", None, -1))
		self.remove_part_sets_Button.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Remove Selected", None, -1))
		self.menuItems.setTitle(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Items", None, -1))
		self.menuEdit.setTitle(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Edit", None, -1))
		self.menuFile.setTitle(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "File", None, -1))
		self.menuViewport_Settings.setTitle(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Viewport", None, -1))
		self.actionAdd_Render_State.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Add Render State", None, -1))
		self.actionAdd_Part_Set.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Add Part Set", None, -1))
		self.actionUndo.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Undo", None, -1))
		self.actionRedo.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Redo", None, -1))
		self.actionOpen_File.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Open", None, -1))
		self.actionOpen_File.setShortcut(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Ctrl+O", None, -1))
		self.actionSave.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Save", None, -1))
		self.actionSave.setShortcut(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Ctrl+Shift+S", None, -1))
		self.actionDelete_Parts.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Delete Selected Part Sets", None, -1))
		self.actionRemove_Selected_States.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Remove Selected States", None, -1))
		self.actionAdd_Asset.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Add Asset", None, -1))
		self.action_Add_Child_Asset.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Add Child Asset", None, -1))
		self.actionRemove_Selected_Asset.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Remove Selected Asset", None, -1))
		self.actionDisplay_Layers_To_Part_Sets.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Display Layers To Part Sets", None, -1))
		self.action_auto_frame_toggle.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Auto Frame", None, -1))
		self.action_Frame_Selected.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Frame Selected", None, -1))
		self.action_Frame_Visable.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Frame Visable", None, -1))
		self.actionLoad.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Load", None, -1))
		self.action_Sync_Display_Layers.setText(QtWidgets.QApplication.translate("Vray_Scene_State_Manager", "Sync Display Layers", None, -1))

from Scripts.Tools.Vray_Scene_States_Manager.Custom_Widgets import Asset_Tree_View, Matte_Overide_View, Part_Sets_List_View, Beauty_Overide_View, Render_States_List_View, Invisible_Overide_View, Entity_Tree_View

if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	Vray_Scene_State_Manager = QtWidgets.QMainWindow()
	ui = Ui_Vray_Scene_State_Manager()
	ui.setupUi(Vray_Scene_State_Manager)
	Vray_Scene_State_Manager.show()
	sys.exit(app.exec_())

