# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dloveridge\Documents\AW_Git_Repo\Maya\Scripts\Tools\Vray_Scene_States_Manager\Vray_Scene_State_Manager.ui'
#
# Created: Mon Dec 28 14:16:47 2015
#      by: pyside-uic 0.2.14 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from QT import QtCore, QtGui

class Ui_Vray_Scene_State_Manager(object):
	def setupUi(self, Vray_Scene_State_Manager):
		Vray_Scene_State_Manager.setObjectName("Vray_Scene_State_Manager")
		Vray_Scene_State_Manager.resize(1344, 871)
		self.centralwidget = QtGui.QWidget(Vray_Scene_State_Manager)
		self.centralwidget.setObjectName("centralwidget")
		self.verticalLayout_10 = QtGui.QVBoxLayout(self.centralwidget)
		self.verticalLayout_10.setObjectName("verticalLayout_10")
		self.splitter_3 = QtGui.QSplitter(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.splitter_3.sizePolicy().hasHeightForWidth())
		self.splitter_3.setSizePolicy(sizePolicy)
		self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
		self.splitter_3.setObjectName("splitter_3")
		self.splitter_2 = QtGui.QSplitter(self.splitter_3)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
		self.splitter_2.setSizePolicy(sizePolicy)
		self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
		self.splitter_2.setHandleWidth(11)
		self.splitter_2.setObjectName("splitter_2")
		self.Asset_Tree_frame = QtGui.QFrame(self.splitter_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(2)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.Asset_Tree_frame.sizePolicy().hasHeightForWidth())
		self.Asset_Tree_frame.setSizePolicy(sizePolicy)
		self.Asset_Tree_frame.setFrameShape(QtGui.QFrame.Box)
		self.Asset_Tree_frame.setFrameShadow(QtGui.QFrame.Plain)
		self.Asset_Tree_frame.setObjectName("Asset_Tree_frame")
		self.verticalLayout_4 = QtGui.QVBoxLayout(self.Asset_Tree_frame)
		self.verticalLayout_4.setSpacing(0)
		self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_4.setObjectName("verticalLayout_4")
		self.Asset_Tree_groupBox = QtGui.QGroupBox(self.Asset_Tree_frame)
		self.Asset_Tree_groupBox.setAlignment(QtCore.Qt.AlignCenter)
		self.Asset_Tree_groupBox.setObjectName("Asset_Tree_groupBox")
		self.verticalLayout_3 = QtGui.QVBoxLayout(self.Asset_Tree_groupBox)
		self.verticalLayout_3.setSpacing(0)
		self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
		self.verticalLayout_3.setObjectName("verticalLayout_3")
		self.asset_tree_view = Asset_Tree_View(self.Asset_Tree_groupBox)
		self.asset_tree_view.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
		self.asset_tree_view.setDefaultDropAction(QtCore.Qt.IgnoreAction)
		self.asset_tree_view.setSortingEnabled(True)
		self.asset_tree_view.setObjectName("asset_tree_view")
		self.verticalLayout_3.addWidget(self.asset_tree_view)
		self.horizontalLayout_2 = QtGui.QHBoxLayout()
		self.horizontalLayout_2.setSpacing(3)
		self.horizontalLayout_2.setObjectName("horizontalLayout_2")
		self.add_asset_Button = QtGui.QPushButton(self.Asset_Tree_groupBox)
		self.add_asset_Button.setObjectName("add_asset_Button")
		self.horizontalLayout_2.addWidget(self.add_asset_Button)
		self.add_child_asset_Button = QtGui.QPushButton(self.Asset_Tree_groupBox)
		self.add_child_asset_Button.setObjectName("add_child_asset_Button")
		self.horizontalLayout_2.addWidget(self.add_child_asset_Button)
		self.verticalLayout_3.addLayout(self.horizontalLayout_2)
		self.remove_asset_Button = QtGui.QPushButton(self.Asset_Tree_groupBox)
		self.remove_asset_Button.setObjectName("remove_asset_Button")
		self.verticalLayout_3.addWidget(self.remove_asset_Button)
		self.verticalLayout_4.addWidget(self.Asset_Tree_groupBox)
		self.Render_States_frame = QtGui.QFrame(self.splitter_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.Render_States_frame.sizePolicy().hasHeightForWidth())
		self.Render_States_frame.setSizePolicy(sizePolicy)
		self.Render_States_frame.setFrameShape(QtGui.QFrame.Box)
		self.Render_States_frame.setFrameShadow(QtGui.QFrame.Plain)
		self.Render_States_frame.setObjectName("Render_States_frame")
		self.verticalLayout_9 = QtGui.QVBoxLayout(self.Render_States_frame)
		self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_9.setObjectName("verticalLayout_9")
		self.Render_States_groupBox = QtGui.QGroupBox(self.Render_States_frame)
		self.Render_States_groupBox.setAlignment(QtCore.Qt.AlignCenter)
		self.Render_States_groupBox.setObjectName("Render_States_groupBox")
		self.Render_Layers_groupBox_verticalLayout = QtGui.QVBoxLayout(self.Render_States_groupBox)
		self.Render_Layers_groupBox_verticalLayout.setSpacing(0)
		self.Render_Layers_groupBox_verticalLayout.setContentsMargins(3, 3, 3, 3)
		self.Render_Layers_groupBox_verticalLayout.setObjectName("Render_Layers_groupBox_verticalLayout")
		self.render_layer_helper_button = QtGui.QPushButton(self.Render_States_groupBox)
		self.render_layer_helper_button.setEnabled(False)
		self.render_layer_helper_button.setObjectName("render_layer_helper_button")
		self.Render_Layers_groupBox_verticalLayout.addWidget(self.render_layer_helper_button)
		self.isolateSelect_Button = QtGui.QPushButton(self.Render_States_groupBox)
		self.isolateSelect_Button.setCheckable(True)
		self.isolateSelect_Button.setObjectName("isolateSelect_Button")
		self.Render_Layers_groupBox_verticalLayout.addWidget(self.isolateSelect_Button)
		self.Hide_Unasined_Layers_Button = QtGui.QPushButton(self.Render_States_groupBox)
		self.Hide_Unasined_Layers_Button.setObjectName("Hide_Unasined_Layers_Button")
		self.Render_Layers_groupBox_verticalLayout.addWidget(self.Hide_Unasined_Layers_Button)
		self.Show_All_Display_Layers_Button = QtGui.QPushButton(self.Render_States_groupBox)
		self.Show_All_Display_Layers_Button.setObjectName("Show_All_Display_Layers_Button")
		self.Render_Layers_groupBox_verticalLayout.addWidget(self.Show_All_Display_Layers_Button)
		self.render_states_view = Render_States_List_View(self.Render_States_groupBox)
		self.render_states_view.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
		self.render_states_view.setObjectName("render_states_view")
		self.Render_Layers_groupBox_verticalLayout.addWidget(self.render_states_view)
		self.horizontalLayout = QtGui.QHBoxLayout()
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.add_render_state_Button = QtGui.QPushButton(self.Render_States_groupBox)
		self.add_render_state_Button.setObjectName("add_render_state_Button")
		self.horizontalLayout.addWidget(self.add_render_state_Button)
		self.remove_render_state_Button = QtGui.QPushButton(self.Render_States_groupBox)
		self.remove_render_state_Button.setObjectName("remove_render_state_Button")
		self.horizontalLayout.addWidget(self.remove_render_state_Button)
		self.Render_Layers_groupBox_verticalLayout.addLayout(self.horizontalLayout)
		self.verticalLayout_9.addWidget(self.Render_States_groupBox)
		self.splitter = QtGui.QSplitter(self.splitter_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
		self.splitter.setSizePolicy(sizePolicy)
		self.splitter.setOrientation(QtCore.Qt.Vertical)
		self.splitter.setObjectName("splitter")
		self.Beauty_Overide_frame = QtGui.QFrame(self.splitter)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.Beauty_Overide_frame.sizePolicy().hasHeightForWidth())
		self.Beauty_Overide_frame.setSizePolicy(sizePolicy)
		self.Beauty_Overide_frame.setFrameShape(QtGui.QFrame.Box)
		self.Beauty_Overide_frame.setFrameShadow(QtGui.QFrame.Plain)
		self.Beauty_Overide_frame.setObjectName("Beauty_Overide_frame")
		self.verticalLayout_5 = QtGui.QVBoxLayout(self.Beauty_Overide_frame)
		self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_5.setObjectName("verticalLayout_5")
		self.Beauty_Overide_groupBox = QtGui.QGroupBox(self.Beauty_Overide_frame)
		self.Beauty_Overide_groupBox.setAlignment(QtCore.Qt.AlignCenter)
		self.Beauty_Overide_groupBox.setObjectName("Beauty_Overide_groupBox")
		self.Beauty_groupBox_verticalLayout = QtGui.QVBoxLayout(self.Beauty_Overide_groupBox)
		self.Beauty_groupBox_verticalLayout.setContentsMargins(3, 3, 3, 3)
		self.Beauty_groupBox_verticalLayout.setObjectName("Beauty_groupBox_verticalLayout")
		self.beauty_overide_view = Beauty_Overide_View(self.Beauty_Overide_groupBox)
		self.beauty_overide_view.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
		self.beauty_overide_view.setDragEnabled(True)
		self.beauty_overide_view.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
		self.beauty_overide_view.setDefaultDropAction(QtCore.Qt.IgnoreAction)
		self.beauty_overide_view.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
		self.beauty_overide_view.setProperty("view_state_type", 1)
		self.beauty_overide_view.setObjectName("beauty_overide_view")
		self.Beauty_groupBox_verticalLayout.addWidget(self.beauty_overide_view)
		self.verticalLayout_5.addWidget(self.Beauty_Overide_groupBox)
		self.Matte_Overide_frame = QtGui.QFrame(self.splitter)
		self.Matte_Overide_frame.setFrameShape(QtGui.QFrame.Box)
		self.Matte_Overide_frame.setFrameShadow(QtGui.QFrame.Plain)
		self.Matte_Overide_frame.setObjectName("Matte_Overide_frame")
		self.verticalLayout_6 = QtGui.QVBoxLayout(self.Matte_Overide_frame)
		self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_6.setObjectName("verticalLayout_6")
		self.Matte_Overide_groupBox = QtGui.QGroupBox(self.Matte_Overide_frame)
		self.Matte_Overide_groupBox.setAlignment(QtCore.Qt.AlignCenter)
		self.Matte_Overide_groupBox.setObjectName("Matte_Overide_groupBox")
		self.Matte_groupBox_verticalLayout = QtGui.QVBoxLayout(self.Matte_Overide_groupBox)
		self.Matte_groupBox_verticalLayout.setContentsMargins(3, 3, 3, 3)
		self.Matte_groupBox_verticalLayout.setObjectName("Matte_groupBox_verticalLayout")
		self.matte_overide_view = Matte_Overide_View(self.Matte_Overide_groupBox)
		self.matte_overide_view.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
		self.matte_overide_view.setDragEnabled(True)
		self.matte_overide_view.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
		self.matte_overide_view.setDefaultDropAction(QtCore.Qt.IgnoreAction)
		self.matte_overide_view.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
		self.matte_overide_view.setProperty("view_state_type", 2)
		self.matte_overide_view.setObjectName("matte_overide_view")
		self.Matte_groupBox_verticalLayout.addWidget(self.matte_overide_view)
		self.verticalLayout_6.addWidget(self.Matte_Overide_groupBox)
		self.Invisible_Overide_frame = QtGui.QFrame(self.splitter)
		self.Invisible_Overide_frame.setFrameShape(QtGui.QFrame.Box)
		self.Invisible_Overide_frame.setFrameShadow(QtGui.QFrame.Plain)
		self.Invisible_Overide_frame.setObjectName("Invisible_Overide_frame")
		self.verticalLayout_7 = QtGui.QVBoxLayout(self.Invisible_Overide_frame)
		self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_7.setObjectName("verticalLayout_7")
		self.Invisible_Overide_groupBox = QtGui.QGroupBox(self.Invisible_Overide_frame)
		self.Invisible_Overide_groupBox.setAlignment(QtCore.Qt.AlignCenter)
		self.Invisible_Overide_groupBox.setObjectName("Invisible_Overide_groupBox")
		self.Invisible_groupBox_verticalLayout = QtGui.QVBoxLayout(self.Invisible_Overide_groupBox)
		self.Invisible_groupBox_verticalLayout.setContentsMargins(3, 3, 3, 3)
		self.Invisible_groupBox_verticalLayout.setObjectName("Invisible_groupBox_verticalLayout")
		self.invisible_overide_view = Invisible_Overide_View(self.Invisible_Overide_groupBox)
		self.invisible_overide_view.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
		self.invisible_overide_view.setDragEnabled(True)
		self.invisible_overide_view.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
		self.invisible_overide_view.setDefaultDropAction(QtCore.Qt.IgnoreAction)
		self.invisible_overide_view.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
		self.invisible_overide_view.setProperty("view_state_type", 3)
		self.invisible_overide_view.setObjectName("invisible_overide_view")
		self.Invisible_groupBox_verticalLayout.addWidget(self.invisible_overide_view)
		self.verticalLayout_7.addWidget(self.Invisible_Overide_groupBox)
		self.Part_Sets_frame = QtGui.QFrame(self.splitter_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(1)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.Part_Sets_frame.sizePolicy().hasHeightForWidth())
		self.Part_Sets_frame.setSizePolicy(sizePolicy)
		self.Part_Sets_frame.setFrameShape(QtGui.QFrame.Box)
		self.Part_Sets_frame.setFrameShadow(QtGui.QFrame.Plain)
		self.Part_Sets_frame.setObjectName("Part_Sets_frame")
		self.verticalLayout_8 = QtGui.QVBoxLayout(self.Part_Sets_frame)
		self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_8.setObjectName("verticalLayout_8")
		self.Part_Sets_groupBox = QtGui.QGroupBox(self.Part_Sets_frame)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.Part_Sets_groupBox.sizePolicy().hasHeightForWidth())
		self.Part_Sets_groupBox.setSizePolicy(sizePolicy)
		self.Part_Sets_groupBox.setAlignment(QtCore.Qt.AlignCenter)
		self.Part_Sets_groupBox.setObjectName("Part_Sets_groupBox")
		self.Part_Sets_groupBox_verticalLayout = QtGui.QVBoxLayout(self.Part_Sets_groupBox)
		self.Part_Sets_groupBox_verticalLayout.setSpacing(0)
		self.Part_Sets_groupBox_verticalLayout.setContentsMargins(3, 3, 3, 3)
		self.Part_Sets_groupBox_verticalLayout.setObjectName("Part_Sets_groupBox_verticalLayout")
		self.part_sets_view = Part_Sets_List_View(self.Part_Sets_groupBox)
		self.part_sets_view.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
		self.part_sets_view.setDragEnabled(True)
		self.part_sets_view.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
		self.part_sets_view.setDefaultDropAction(QtCore.Qt.IgnoreAction)
		self.part_sets_view.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
		self.part_sets_view.setProperty("view_state_type", 0)
		self.part_sets_view.setObjectName("part_sets_view")
		self.Part_Sets_groupBox_verticalLayout.addWidget(self.part_sets_view)
		self.horizontalLayout_3 = QtGui.QHBoxLayout()
		self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.add_part_set_Button = QtGui.QPushButton(self.Part_Sets_groupBox)
		self.add_part_set_Button.setObjectName("add_part_set_Button")
		self.horizontalLayout_3.addWidget(self.add_part_set_Button)
		self.remove_part_sets_Button = QtGui.QPushButton(self.Part_Sets_groupBox)
		self.remove_part_sets_Button.setObjectName("remove_part_sets_Button")
		self.horizontalLayout_3.addWidget(self.remove_part_sets_Button)
		self.Part_Sets_groupBox_verticalLayout.addLayout(self.horizontalLayout_3)
		self.verticalLayout_8.addWidget(self.Part_Sets_groupBox)
		self.verticalGroupBox = QtGui.QGroupBox(self.splitter_3)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(5)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.verticalGroupBox.sizePolicy().hasHeightForWidth())
		self.verticalGroupBox.setSizePolicy(sizePolicy)
		self.verticalGroupBox.setObjectName("verticalGroupBox")
		self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalGroupBox)
		self.verticalLayout_2.setSpacing(0)
		self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.verticalLayout = QtGui.QVBoxLayout()
		self.verticalLayout.setSpacing(0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.horizontalWidget = QtGui.QWidget(self.verticalGroupBox)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
		self.horizontalWidget.setSizePolicy(sizePolicy)
		self.horizontalWidget.setObjectName("horizontalWidget")
		self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalWidget)
		self.horizontalLayout_4.setSpacing(6)
		self.horizontalLayout_4.setContentsMargins(3, 3, 3, 3)
		self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout_4.setObjectName("horizontalLayout_4")
		self.toolButton = ToolButton(self.horizontalWidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
		self.toolButton.setSizePolicy(sizePolicy)
		self.toolButton.setPopupMode(QtGui.QToolButton.InstantPopup)
		self.toolButton.setObjectName("toolButton")
		self.horizontalLayout_4.addWidget(self.toolButton)
		self.toolButton_2 = Camera_List_ToolButton(self.horizontalWidget)
		self.toolButton_2.setPopupMode(QtGui.QToolButton.InstantPopup)
		self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
		self.toolButton_2.setArrowType(QtCore.Qt.DownArrow)
		self.toolButton_2.setObjectName("toolButton_2")
		self.horizontalLayout_4.addWidget(self.toolButton_2)
		self.Auto_Frame_Toggle_Button = QtGui.QPushButton(self.horizontalWidget)
		self.Auto_Frame_Toggle_Button.setCheckable(True)
		self.Auto_Frame_Toggle_Button.setObjectName("Auto_Frame_Toggle_Button")
		self.horizontalLayout_4.addWidget(self.Auto_Frame_Toggle_Button)
		spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_4.addItem(spacerItem)
		self.verticalLayout.addWidget(self.horizontalWidget)
		self.Model_Editor = Maya_Modle_Editor(self.verticalGroupBox)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(1)
		sizePolicy.setHeightForWidth(self.Model_Editor.sizePolicy().hasHeightForWidth())
		self.Model_Editor.setSizePolicy(sizePolicy)
		self.Model_Editor.setMinimumSize(QtCore.QSize(492, 556))
		self.Model_Editor.setStyleSheet("background-color: rgb(0, 0, 0);")
		self.Model_Editor.setProperty("Auto_Frame_Value", False)
		self.Model_Editor.setObjectName("Model_Editor")
		self.verticalLayout_12 = QtGui.QVBoxLayout(self.Model_Editor)
		self.verticalLayout_12.setObjectName("verticalLayout_12")
		self.verticalLayout.addWidget(self.Model_Editor)
		self.verticalLayout_2.addLayout(self.verticalLayout)
		self.frame_2 = QtGui.QFrame(self.verticalGroupBox)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
		self.frame_2.setSizePolicy(sizePolicy)
		self.frame_2.setFrameShape(QtGui.QFrame.Box)
		self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
		self.frame_2.setObjectName("frame_2")
		self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frame_2)
		self.horizontalLayout_8.setSpacing(1)
		self.horizontalLayout_8.setContentsMargins(1, 1, 1, 1)
		self.horizontalLayout_8.setObjectName("horizontalLayout_8")
		self.Frame_Selected_Button = QtGui.QPushButton(self.frame_2)
		self.Frame_Selected_Button.setObjectName("Frame_Selected_Button")
		self.horizontalLayout_8.addWidget(self.Frame_Selected_Button)
		self.Frame_Visable_Button = QtGui.QPushButton(self.frame_2)
		self.Frame_Visable_Button.setObjectName("Frame_Visable_Button")
		self.horizontalLayout_8.addWidget(self.Frame_Visable_Button)
		self.verticalLayout_2.addWidget(self.frame_2)
		self.verticalLayout_10.addWidget(self.splitter_3)
		self.entity_tree_view = Entity_Tree_View(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.entity_tree_view.sizePolicy().hasHeightForWidth())
		self.entity_tree_view.setSizePolicy(sizePolicy)
		self.entity_tree_view.setObjectName("entity_tree_view")
		self.verticalLayout_10.addWidget(self.entity_tree_view)
		Vray_Scene_State_Manager.setCentralWidget(self.centralwidget)
		self.menubar = QtGui.QMenuBar(Vray_Scene_State_Manager)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 1344, 26))
		self.menubar.setObjectName("menubar")
		self.menuItems = QtGui.QMenu(self.menubar)
		self.menuItems.setObjectName("menuItems")
		self.menuEdit = QtGui.QMenu(self.menubar)
		self.menuEdit.setObjectName("menuEdit")
		self.menuFile = QtGui.QMenu(self.menubar)
		self.menuFile.setObjectName("menuFile")
		self.menuViewport_Settings = QtGui.QMenu(self.menubar)
		self.menuViewport_Settings.setEnabled(False)
		self.menuViewport_Settings.setObjectName("menuViewport_Settings")
		Vray_Scene_State_Manager.setMenuBar(self.menubar)
		self.statusbar = QtGui.QStatusBar(Vray_Scene_State_Manager)
		self.statusbar.setObjectName("statusbar")
		Vray_Scene_State_Manager.setStatusBar(self.statusbar)
		self.actionAdd_Render_State = QtGui.QAction(Vray_Scene_State_Manager)
		self.actionAdd_Render_State.setObjectName("actionAdd_Render_State")
		self.actionAdd_Part_Set = QtGui.QAction(Vray_Scene_State_Manager)
		self.actionAdd_Part_Set.setObjectName("actionAdd_Part_Set")
		self.actionUndo = QtGui.QAction(Vray_Scene_State_Manager)
		self.actionUndo.setEnabled(False)
		self.actionUndo.setObjectName("actionUndo")
		self.actionRedo = QtGui.QAction(Vray_Scene_State_Manager)
		self.actionRedo.setEnabled(False)
		self.actionRedo.setObjectName("actionRedo")
		self.actionOpen_File = QtGui.QAction(Vray_Scene_State_Manager)
		self.actionOpen_File.setEnabled(False)
		self.actionOpen_File.setObjectName("actionOpen_File")
		self.actionSave = QtGui.QAction(Vray_Scene_State_Manager)
		self.actionSave.setEnabled(True)
		self.actionSave.setObjectName("actionSave")
		self.actionDelete_Parts = QtGui.QAction(Vray_Scene_State_Manager)
		self.actionDelete_Parts.setObjectName("actionDelete_Parts")
		self.actionRemove_Selected_States = QtGui.QAction(Vray_Scene_State_Manager)
		self.actionRemove_Selected_States.setObjectName("actionRemove_Selected_States")
		self.actionAdd_Asset = QtGui.QAction(Vray_Scene_State_Manager)
		self.actionAdd_Asset.setObjectName("actionAdd_Asset")
		self.action_Add_Child_Asset = QtGui.QAction(Vray_Scene_State_Manager)
		self.action_Add_Child_Asset.setObjectName("action_Add_Child_Asset")
		self.actionRemove_Selected_Asset = QtGui.QAction(Vray_Scene_State_Manager)
		self.actionRemove_Selected_Asset.setObjectName("actionRemove_Selected_Asset")
		self.actionDisplay_Layers_To_Part_Sets = QtGui.QAction(Vray_Scene_State_Manager)
		self.actionDisplay_Layers_To_Part_Sets.setObjectName("actionDisplay_Layers_To_Part_Sets")
		self.action_auto_frame_toggle = QtGui.QAction(Vray_Scene_State_Manager)
		self.action_auto_frame_toggle.setCheckable(True)
		self.action_auto_frame_toggle.setObjectName("action_auto_frame_toggle")
		self.action_Frame_Selected = QtGui.QAction(Vray_Scene_State_Manager)
		self.action_Frame_Selected.setObjectName("action_Frame_Selected")
		self.action_Frame_Visable = QtGui.QAction(Vray_Scene_State_Manager)
		self.action_Frame_Visable.setObjectName("action_Frame_Visable")
		self.actionLoad = QtGui.QAction(Vray_Scene_State_Manager)
		self.actionLoad.setObjectName("actionLoad")
		self.action_Sync_Display_Layers = QtGui.QAction(Vray_Scene_State_Manager)
		self.action_Sync_Display_Layers.setObjectName("action_Sync_Display_Layers")
		self.menuItems.addAction(self.actionAdd_Asset)
		self.menuItems.addAction(self.action_Add_Child_Asset)
		self.menuItems.addAction(self.actionRemove_Selected_Asset)
		self.menuItems.addAction(self.actionAdd_Part_Set)
		self.menuItems.addAction(self.actionDelete_Parts)
		self.menuItems.addAction(self.actionAdd_Render_State)
		self.menuItems.addAction(self.actionRemove_Selected_States)
		self.menuItems.addAction(self.actionDisplay_Layers_To_Part_Sets)
		self.menuItems.addAction(self.action_Sync_Display_Layers)
		self.menuEdit.addAction(self.actionUndo)
		self.menuEdit.addAction(self.actionRedo)
		self.menuEdit.addSeparator()
		self.menuFile.addAction(self.actionSave)
		self.menuFile.addAction(self.actionLoad)
		self.menuViewport_Settings.addAction(self.action_Frame_Selected)
		self.menuViewport_Settings.addAction(self.action_Frame_Visable)
		self.menuViewport_Settings.addAction(self.action_auto_frame_toggle)
		self.menubar.addAction(self.menuFile.menuAction())
		self.menubar.addAction(self.menuItems.menuAction())
		self.menubar.addAction(self.menuEdit.menuAction())
		self.menubar.addAction(self.menuViewport_Settings.menuAction())

		self.retranslateUi(Vray_Scene_State_Manager)
		QtCore.QObject.connect(self.actionAdd_Part_Set, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.add_Part_Set)
		QtCore.QObject.connect(self.actionUndo, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.undo_it)
		QtCore.QObject.connect(self.actionRedo, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.redo_it)
		QtCore.QObject.connect(self.actionAdd_Render_State, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.add_Render_State)
		QtCore.QObject.connect(self.actionOpen_File, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.open_File)
		QtCore.QObject.connect(self.actionSave, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.Save)
		QtCore.QObject.connect(self.actionDelete_Parts, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.Remove_Selected_Part_Sets)
		QtCore.QObject.connect(self.actionRemove_Selected_States, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.Remove_Selected_Render_States)
		QtCore.QObject.connect(self.actionAdd_Asset, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.add_Asset)
		QtCore.QObject.connect(self.add_render_state_Button, QtCore.SIGNAL("clicked()"), self.actionAdd_Render_State.trigger)
		QtCore.QObject.connect(self.remove_render_state_Button, QtCore.SIGNAL("clicked()"), self.actionRemove_Selected_States.trigger)
		QtCore.QObject.connect(self.add_part_set_Button, QtCore.SIGNAL("clicked()"), self.actionAdd_Part_Set.trigger)
		QtCore.QObject.connect(self.remove_part_sets_Button, QtCore.SIGNAL("clicked()"), self.actionDelete_Parts.trigger)
		QtCore.QObject.connect(Vray_Scene_State_Manager, QtCore.SIGNAL("ACTIVATE_RUN_SETUP(QMainWindow*)"), self.entity_tree_view._run_setup)
		QtCore.QObject.connect(Vray_Scene_State_Manager, QtCore.SIGNAL("ACTIVATE_RUN_SETUP(QMainWindow*)"), self.beauty_overide_view._run_setup)
		QtCore.QObject.connect(Vray_Scene_State_Manager, QtCore.SIGNAL("ACTIVATE_RUN_SETUP(QMainWindow*)"), self.matte_overide_view._run_setup)
		QtCore.QObject.connect(Vray_Scene_State_Manager, QtCore.SIGNAL("ACTIVATE_RUN_SETUP(QMainWindow*)"), self.invisible_overide_view._run_setup)
		QtCore.QObject.connect(Vray_Scene_State_Manager, QtCore.SIGNAL("ACTIVATE_RUN_SETUP(QMainWindow*)"), self.part_sets_view._run_setup)
		QtCore.QObject.connect(Vray_Scene_State_Manager, QtCore.SIGNAL("ACTIVATE_RUN_SETUP(QMainWindow*)"), self.render_states_view._run_setup)
		QtCore.QObject.connect(Vray_Scene_State_Manager, QtCore.SIGNAL("ACTIVATE_RUN_SETUP(QMainWindow*)"), self.asset_tree_view._run_setup)
		QtCore.QObject.connect(self.action_Add_Child_Asset, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.add_Child_Asset)
		QtCore.QObject.connect(self.add_child_asset_Button, QtCore.SIGNAL("clicked()"), self.action_Add_Child_Asset.trigger)
		QtCore.QObject.connect(self.add_asset_Button, QtCore.SIGNAL("clicked()"), self.actionAdd_Asset.trigger)
		QtCore.QObject.connect(self.asset_tree_view, QtCore.SIGNAL("ACTIVE_ITEM_CHANGED(QStandardItem*)"), self.render_states_view.Update_On_Active_Item_Changed)
		QtCore.QObject.connect(self.render_states_view, QtCore.SIGNAL("ACTIVE_ITEM_CHANGED(QStandardItem*)"), self.beauty_overide_view.Update_On_Active_Item_Changed)
		QtCore.QObject.connect(self.render_states_view, QtCore.SIGNAL("ACTIVE_ITEM_CHANGED(QStandardItem*)"), self.matte_overide_view.Update_On_Active_Item_Changed)
		QtCore.QObject.connect(self.render_states_view, QtCore.SIGNAL("ACTIVE_ITEM_CHANGED(QStandardItem*)"), self.invisible_overide_view.Update_On_Active_Item_Changed)
		QtCore.QObject.connect(self.render_states_view, QtCore.SIGNAL("ACTIVE_ITEM_CHANGED(QStandardItem*)"), self.part_sets_view.Update_On_Active_Item_Changed)
		QtCore.QObject.connect(self.actionRemove_Selected_Asset, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.Remove_Selected_Assets)
		QtCore.QObject.connect(self.remove_asset_Button, QtCore.SIGNAL("clicked()"), self.actionRemove_Selected_Asset.trigger)
		QtCore.QObject.connect(Vray_Scene_State_Manager, QtCore.SIGNAL("ACTIVATE_RUN_SETUP(QMainWindow*)"), self.Model_Editor._run_setup)
		QtCore.QObject.connect(self.actionDisplay_Layers_To_Part_Sets, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.Construct_From_Display_Layers)
		QtCore.QObject.connect(self.Auto_Frame_Toggle_Button, QtCore.SIGNAL("toggled(bool)"), self.action_auto_frame_toggle.setChecked)
		QtCore.QObject.connect(self.action_auto_frame_toggle, QtCore.SIGNAL("toggled(bool)"), self.Auto_Frame_Toggle_Button.setChecked)
		QtCore.QObject.connect(self.action_Frame_Selected, QtCore.SIGNAL("triggered()"), self.Model_Editor.Viewfit_Frame_Selected)
		QtCore.QObject.connect(self.action_Frame_Visable, QtCore.SIGNAL("triggered()"), self.Model_Editor.Viewfit_Frame_All)
		QtCore.QObject.connect(self.Frame_Selected_Button, QtCore.SIGNAL("clicked()"), self.action_Frame_Selected.trigger)
		QtCore.QObject.connect(self.Frame_Visable_Button, QtCore.SIGNAL("clicked()"), self.action_Frame_Visable.trigger)
		QtCore.QObject.connect(self.action_auto_frame_toggle, QtCore.SIGNAL("toggled(bool)"), self.Model_Editor.set_Auto_Frame_Value)
		QtCore.QObject.connect(self.actionLoad, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.Load)
		QtCore.QObject.connect(self.action_Sync_Display_Layers, QtCore.SIGNAL("triggered()"), Vray_Scene_State_Manager.sync_Display_Layers)
		QtCore.QObject.connect(self.Hide_Unasined_Layers_Button, QtCore.SIGNAL("clicked()"), Vray_Scene_State_Manager.Apply_Current_State_To_Diaplay_Layers)
		QtCore.QObject.connect(self.Show_All_Display_Layers_Button, QtCore.SIGNAL("clicked()"), Vray_Scene_State_Manager.Show_All_Diaplay_Layers)
		QtCore.QMetaObject.connectSlotsByName(Vray_Scene_State_Manager)

	def retranslateUi(self, Vray_Scene_State_Manager):
		Vray_Scene_State_Manager.setWindowTitle(QtGui.QApplication.translate("Vray_Scene_State_Manager", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
		self.Asset_Tree_groupBox.setTitle(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Asset Tree", None, QtGui.QApplication.UnicodeUTF8))
		self.add_asset_Button.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Add Asset", None, QtGui.QApplication.UnicodeUTF8))
		self.add_child_asset_Button.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Add Child Asset", None, QtGui.QApplication.UnicodeUTF8))
		self.remove_asset_Button.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Remove Selected Asset", None, QtGui.QApplication.UnicodeUTF8))
		self.Render_States_groupBox.setTitle(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Render States", None, QtGui.QApplication.UnicodeUTF8))
		self.render_layer_helper_button.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Build Render Layer Helper", None, QtGui.QApplication.UnicodeUTF8))
		self.isolateSelect_Button.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Isolate Selected", None, QtGui.QApplication.UnicodeUTF8))
		self.Hide_Unasined_Layers_Button.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Hide Unasined", None, QtGui.QApplication.UnicodeUTF8))
		self.Show_All_Display_Layers_Button.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Show All Display Layers", None, QtGui.QApplication.UnicodeUTF8))
		self.add_render_state_Button.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Add Render State", None, QtGui.QApplication.UnicodeUTF8))
		self.remove_render_state_Button.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Remove Selected", None, QtGui.QApplication.UnicodeUTF8))
		self.Beauty_Overide_groupBox.setTitle(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Beauty Part Sets", None, QtGui.QApplication.UnicodeUTF8))
		self.Matte_Overide_groupBox.setTitle(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Matte Part Sets", None, QtGui.QApplication.UnicodeUTF8))
		self.Invisible_Overide_groupBox.setTitle(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Invisible Part Sets", None, QtGui.QApplication.UnicodeUTF8))
		self.Part_Sets_groupBox.setTitle(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Unasied Part Sets", None, QtGui.QApplication.UnicodeUTF8))
		self.add_part_set_Button.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Add Part Set", None, QtGui.QApplication.UnicodeUTF8))
		self.remove_part_sets_Button.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Remove Selected", None, QtGui.QApplication.UnicodeUTF8))
		self.verticalGroupBox.setTitle(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Active Part Set Item View", None, QtGui.QApplication.UnicodeUTF8))
		self.toolButton.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Display Apperence", None, QtGui.QApplication.UnicodeUTF8))
		self.toolButton_2.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Set Active Camera", None, QtGui.QApplication.UnicodeUTF8))
		self.Auto_Frame_Toggle_Button.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Auto Frame", None, QtGui.QApplication.UnicodeUTF8))
		self.Frame_Selected_Button.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Frame Selected", None, QtGui.QApplication.UnicodeUTF8))
		self.Frame_Visable_Button.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Frame Visable", None, QtGui.QApplication.UnicodeUTF8))
		self.menuItems.setTitle(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Items", None, QtGui.QApplication.UnicodeUTF8))
		self.menuEdit.setTitle(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Edit", None, QtGui.QApplication.UnicodeUTF8))
		self.menuFile.setTitle(QtGui.QApplication.translate("Vray_Scene_State_Manager", "File", None, QtGui.QApplication.UnicodeUTF8))
		self.menuViewport_Settings.setTitle(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Viewport", None, QtGui.QApplication.UnicodeUTF8))
		self.actionAdd_Render_State.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Add Render State", None, QtGui.QApplication.UnicodeUTF8))
		self.actionAdd_Part_Set.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Add Part Set", None, QtGui.QApplication.UnicodeUTF8))
		self.actionUndo.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Undo", None, QtGui.QApplication.UnicodeUTF8))
		self.actionRedo.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Redo", None, QtGui.QApplication.UnicodeUTF8))
		self.actionOpen_File.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Open", None, QtGui.QApplication.UnicodeUTF8))
		self.actionOpen_File.setShortcut(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
		self.actionSave.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Save", None, QtGui.QApplication.UnicodeUTF8))
		self.actionSave.setShortcut(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
		self.actionDelete_Parts.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Delete Selected Part Sets", None, QtGui.QApplication.UnicodeUTF8))
		self.actionRemove_Selected_States.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Remove Selected States", None, QtGui.QApplication.UnicodeUTF8))
		self.actionAdd_Asset.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Add Asset", None, QtGui.QApplication.UnicodeUTF8))
		self.action_Add_Child_Asset.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Add Child Asset", None, QtGui.QApplication.UnicodeUTF8))
		self.actionRemove_Selected_Asset.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Remove Selected Asset", None, QtGui.QApplication.UnicodeUTF8))
		self.actionDisplay_Layers_To_Part_Sets.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Display Layers To Part Sets", None, QtGui.QApplication.UnicodeUTF8))
		self.action_auto_frame_toggle.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Auto Frame", None, QtGui.QApplication.UnicodeUTF8))
		self.action_Frame_Selected.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Frame Selected", None, QtGui.QApplication.UnicodeUTF8))
		self.action_Frame_Visable.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Frame Visable", None, QtGui.QApplication.UnicodeUTF8))
		self.actionLoad.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Load", None, QtGui.QApplication.UnicodeUTF8))
		self.action_Sync_Display_Layers.setText(QtGui.QApplication.translate("Vray_Scene_State_Manager", "Sync Display Layers", None, QtGui.QApplication.UnicodeUTF8))

from Scripts.Tools.Vray_Scene_States_Manager.Custom_Widgets import Asset_Tree_View, Matte_Overide_View, Entity_Tree_View, Part_Sets_List_View, Beauty_Overide_View, Maya_Modle_Editor, Render_States_List_View, Invisible_Overide_View, Camera_List_ToolButton, ToolButton

if __name__ == "__main__":
	import sys
	app = QtGui.QApplication(sys.argv)
	Vray_Scene_State_Manager = QtGui.QMainWindow()
	ui = Ui_Vray_Scene_State_Manager()
	ui.setupUi(Vray_Scene_State_Manager)
	Vray_Scene_State_Manager.show()
	sys.exit(app.exec_())

